### ISSUE TITLE
send data to elastic index

### ISSUE THREAD

**Issue by markusTh83** [elastic/Machinebeat#29]
Hi Felix,

one more problem on my side:
I'm not able to write the collected data to an index differing from machinebeat-*

I've tried:
```
setup.template.pattern: "my_index-*"
setup.template.name: "my_index"
```
with a created index mapping:

```
{
  "index_patterns": [
    "my_index-*"
  ],
  "mappings": {
    "_meta": {
      "beat": "my_index",
      "version": "7.10.1"
    },
    "_source": {
      "enabled": false
    },
    "date_detection": false
  },
  "order": 1,
  "settings": {
    "index": {
      "lifecycle": {
        "name": "my_index_rollover",
        "rollover_alias": "my_index_rollover"
      },
      "number_of_shards": 1
    },
      "number_of_shards": 1
  }
}
```
and also with the standard setting of 
```
setup.template.pattern: "machinebeat-*"
setup.template.name: "machinebeat"
```

my output setting is
```
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["my.elastic.server:9200"]
  index: "my_index-%{[agent.version]}-%{+yyyy_MM}"

  username: "uname"
  password: "pwd"
```
What am I doing wrong?

Thank you :D
