### ISSUE TITLE
Code for PLC4x

### ISSUE THREAD

**Issue by meteoricfarm** [elastic/Machinebeat#55]
Dear Contributors,

First of all, Happy New Year!

I'd like to use PLC4x modules, but I cannot find any relevant code for explanation.
Does anyone guide me to use plc4x modules for Machinebeat?

Sincerely,

**Comment by felix-lessoer** [comment]
Hey @meteoricfarm 

thanks for considering Machinebeat. 
Can you elaborate a little more on what you would like to achieve?
Very general speaking you need to enable and change the plc4x config file to get it up and running.
plc4x offers various connectors to other protocols. There might be differences based on what you finally wanna use.

**Comment by meteoricfarm** [comment]
Hi Felix,

I'd like to get values from the ModBus TCP server and send them up to Elasticsearch.

Sincerely,

**Comment by felix-lessoer** [comment]
I tested using this config and a local modbus server

modules.d/plc4x.yml
```
# Module: plc4x

- module: plc4x
  metricsets: ["value"]
  enabled: true
  period: 5s

  #The URL of your PLC4X Endpoint
  endpoint: "modbus-tcp://localhost"

  #==========================  Node configuration ============================
  nodes:
  -  tag: "holding-register:1:REAL"
```

You need to change the endpoint and the nodes.
